### ISSUE TITLE
support CB ttl long than 30days

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/loopback-cache#46]
There is a limitation of CB TTL: http://docs.couchbase.com/sdk-api/couchbase-node-client-2.1.2/Bucket.html#touch

So if you want a TTL > 30day, CB will see it as an absolute time from epoch.
My idea is the `mixin` checks the `option.ttl` if it's > 30 days, we see it as a delta, i.e. reset `expiry` to Date.now() + option.ttl.

@makara

**Comment by xavierchow** [comment]
Done with v0.2.1, @makara can you help to pubilsh to npm?

**Comment by makara** [comment]
can you give me your npm username? I can add you as a maintainer.

another thing, you forgot to update the changelog.

**Comment by xavierchow** [comment]
my npm account: xavierchow

**Comment by makara** [comment]
invited

**Comment by xavierchow** [comment]
shipped with v0.2.1, closing.
